[build]
builder = "nixpacks"
buildCommand = "./gradlew clean build -x check -x test"

[deploy]
startCommand = "java -jar build/libs/*.jar --spring.profiles.active=prod"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300

[nixpacks]
jdk = 23